schema_version = "1.0.0"

id = "LZ_Generate_Shapekeys"
version = "1.0.0"
name = "Generate Shape Keys"
tagline = "Generate blank shapekeys for the 52 ARKit blendshapes on your mesh"
maintainer = "lunazera"
type = "add-on"
website = "https://git.gay/lunazera/Blender-Generate-Shapekeys"

blender_version_min = "3.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]